function esc(s) {
    return String(s == null ? '' : s)
        .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}
function chipClass(v) {
    const s = String(v || '').toLowerCase()
    if (/(pass|approve|done|success|up)/.test(s)) return 'pos'
    if (/(fail|reject|blocked|failure|unhealthy|critical)/.test(s)) return 'neg'
    return 'neu'
}
function mdList(items) {
    return items && items.length ? items.map(x => `- ${x}`).join('\n') : '_None._'
}
function htmlList(items) {
    return items && items.length
        ? `<ul>${items.map(x => `<li>${esc(x)}</li>`).join('')}</ul>`
        : '<p class="muted">None.</p>'
}
function paras(text) {
    const t = String(text || '').trim()
    if (!t) return ''
    return t.split(/\n\n+/).map(p => `<p>${esc(p).replace(/\n/g, '<br>')}</p>`).join('')
}

export function buildMarkdown(r) {
    const plan = r.plan, review = r.review, deploy = r.deploy
    const planRepos = (plan.repos || []).map(p => [
        `### ${p.name} — ${p.needsChanges ? 'changes planned' : 'no changes'}`,
        p.scope || '',
        `**Tasks**\n${mdList(p.tasks)}`,
        `**Risks**\n${mdList(p.risks)}`,
    ].join('\n\n')).join('\n\n')

    const impls = (r.implementations || []).map(i => [
        `### ${i.repo} — ${i.status} (tests ${i.testsPassed ? 'passed' : 'failed'})`,
        i.summary || '',
        `**Files changed**\n${mdList(i.filesChanged)}`,
        i.testsRun ? `**Tests:** ${i.testsRun}` : '',
        `**Follow-ups**\n${mdList(i.followups)}`,
    ].filter(Boolean).join('\n\n')).join('\n\n') || '_No repos required changes._'

    const findings = (review.findings || []).map(f =>
        `- **[${f.severity}]** ${f.repo}${f.file ? ` (${f.file})` : ''}: ${f.issue}${f.suggestion ? ` — _${f.suggestion}_` : ''}`,
    ).join('\n') || '_None._'

    const services = (deploy.services || []).map(s => `- ${s.name}: ${s.status}`).join('\n') || '_None._'
    const smoke = (deploy.smokeTests || []).map(s => `- ${s.passed ? '✅' : '❌'} ${s.name}`).join('\n') || '_None._'

    return [
        `# ${r.changeRequest ? r.changeRequest.split('\n')[0].slice(0, 80) : 'Full-stack change'} — Ship Report`,
        `**Change request:**\n\n${r.changeRequest || '—'}`,
        `## Plan`,
        plan.summary || '',
        planRepos,
        plan.openQuestions && plan.openQuestions.length ? `### Open questions\n${mdList(plan.openQuestions)}` : '',
        `## Implementation`,
        impls,
        `## Code review`,
        `**Verdict:** ${review.verdict}`,
        review.summary || '',
        `**Findings**\n${findings}`,
        `## Deployment test (Docker)`,
        `**Status:** ${deploy.status} · **build:** ${deploy.dockerBuild}`,
        `**Services**\n${services}`,
        `**Smoke tests**\n${smoke}`,
        deploy.logsSummary || '',
        `---\n_Generated by the full-stack-ship workflow._`,
    ].filter(Boolean).join('\n\n') + '\n'
}

export function buildHtml(r) {
    const plan = r.plan, review = r.review, deploy = r.deploy
    const planCards = (plan.repos || []).map(p => `
      <article class="card">
        <div class="card-h"><h3>${esc(p.name)}</h3><span class="chip ${p.needsChanges ? 'neu' : 'pos'}">${p.needsChanges ? 'changes planned' : 'no changes'}</span></div>
        ${paras(p.scope)}
        ${p.tasks && p.tasks.length ? `<h4>Tasks</h4>${htmlList(p.tasks)}` : ''}
        ${p.risks && p.risks.length ? `<h4>Risks</h4>${htmlList(p.risks)}` : ''}
      </article>`).join('')

    const implCards = (r.implementations || []).map(i => `
      <article class="card">
        <div class="card-h"><h3>${esc(i.repo)}</h3><span class="chip ${chipClass(i.status)}">${esc(i.status)} · tests ${i.testsPassed ? 'passed' : 'failed'}</span></div>
        ${paras(i.summary)}
        ${i.filesChanged && i.filesChanged.length ? `<h4>Files changed</h4>${htmlList(i.filesChanged)}` : ''}
        ${i.testsRun ? `<p class="muted">${esc(i.testsRun)}</p>` : ''}
        ${i.followups && i.followups.length ? `<h4>Follow-ups</h4>${htmlList(i.followups)}` : ''}
      </article>`).join('') || '<p class="muted">No repos required changes.</p>'

    const findings = (review.findings || []).map(f => `
      <li><span class="chip ${chipClass(f.severity)}">${esc(f.severity)}</span> <strong>${esc(f.repo)}</strong>${f.file ? ` (${esc(f.file)})` : ''}: ${esc(f.issue)}${f.suggestion ? ` — <em>${esc(f.suggestion)}</em>` : ''}</li>`).join('')

    const services = (deploy.services || []).map(s => `<tr><th>${esc(s.name)}</th><td><span class="chip ${chipClass(s.status)}">${esc(s.status)}</span></td></tr>`).join('')
    const smoke = (deploy.smokeTests || []).map(s => `<li>${s.passed ? '✅' : '❌'} ${esc(s.name)}</li>`).join('')

    const css = `
    *{box-sizing:border-box}
    body{margin:0;background:#fbfaf7;color:#1a1a1a;font:16px/1.65 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
    main{max-width:820px;margin:0 auto;padding:64px 24px 96px}
    .masthead{border-bottom:2px solid #1a1a1a;padding-bottom:24px;margin-bottom:8px}
    .eyebrow{letter-spacing:.12em;text-transform:uppercase;font-size:12px;color:#6b6b6b;margin:0 0 6px}
    h1{font:700 38px/1.15 Georgia,"Times New Roman",serif;margin:0 0 16px}
    h2{font:700 22px/1.3 Georgia,serif;margin:48px 0 12px;padding-bottom:6px;border-bottom:1px solid #e6e3dd}
    h3{font-size:16px;margin:0}
    h4{font-size:12px;text-transform:uppercase;letter-spacing:.07em;color:#6b6b6b;margin:18px 0 6px}
    p{margin:0 0 14px}.muted{color:#6b6b6b}
    .chip{display:inline-block;padding:3px 12px;border-radius:999px;font-size:13px;font-weight:600}
    .rating{font-size:18px;padding:6px 18px}
    .chip.pos{background:#e8f5ee;color:#0a7f3f}.chip.neg{background:#fbeceb;color:#b3261e}.chip.neu{background:#fdf3da;color:#8a6d00}
    ul{margin:0 0 14px;padding-left:20px}li{margin:4px 0}
    table.kv{width:100%;border-collapse:collapse;margin:0 0 16px}
    table.kv th{text-align:left;width:160px;color:#6b6b6b;font-weight:600;vertical-align:top;padding:6px 12px 6px 0}
    table.kv td{padding:6px 0}
    .cards{display:grid;gap:20px}
    .card{border:1px solid #e6e3dd;border-radius:10px;padding:20px;background:#fff}
    .card-h{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:8px}
    footer{margin-top:64px;padding-top:16px;border-top:1px solid #e6e3dd;color:#6b6b6b;font-size:12px}`

    return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Full-stack ship report</title>
<style>${css}</style>
</head>
<body>
<main>
  <header class="masthead">
    <p class="eyebrow">Full-stack ship · frontend · backend · deployment</p>
    <h1>Ship report</h1>
    <div><span class="rating chip ${chipClass(deploy.status)}">deploy: ${esc(deploy.status)}</span> <span class="rating chip ${chipClass(review.verdict)}">review: ${esc(review.verdict)}</span></div>
  </header>

  <section>
    <h2>Change request</h2>
    ${paras(r.changeRequest)}
  </section>

  <section>
    <h2>Plan</h2>
    ${paras(plan.summary)}
    <div class="cards">${planCards}
    </div>
    ${plan.openQuestions && plan.openQuestions.length ? `<h4>Open questions</h4>${htmlList(plan.openQuestions)}` : ''}
  </section>

  <section>
    <h2>Implementation</h2>
    <div class="cards">${implCards}
    </div>
  </section>

  <section>
    <h2>Code review</h2>
    <p><span class="chip ${chipClass(review.verdict)}">${esc(review.verdict)}</span></p>
    ${paras(review.summary)}
    ${findings ? `<ul>${findings}</ul>` : '<p class="muted">No findings.</p>'}
  </section>

  <section>
    <h2>Deployment test (Docker)</h2>
    <p><span class="chip ${chipClass(deploy.status)}">${esc(deploy.status)}</span> · build: ${esc(deploy.dockerBuild)}</p>
    ${services ? `<table class="kv">${services}</table>` : ''}
    ${smoke ? `<h4>Smoke tests</h4><ul>${smoke}</ul>` : ''}
    ${paras(deploy.logsSummary)}
  </section>

  <footer>Generated by the full-stack-ship workflow</footer>
</main>
</body>
</html>
`
}
