function esc(s) {
    return String(s == null ? '' : s)
        .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}
function mdList(items) {
    return items && items.length ? items.map(x => `- ${x}`).join('\n') : '_None._'
}
function htmlList(items) {
    return items && items.length
        ? `<ul>${items.map(x => `<li>${esc(x)}</li>`).join('')}</ul>`
        : '<p class="muted">None.</p>'
}
function paras(text) {
    const t = String(text || '').trim()
    if (!t) return ''
    return t.split(/\n\n+/).map(p => `<p>${esc(p).replace(/\n/g, '<br>')}</p>`).join('')
}
function link(url, label) {
    const u = String(url || '').trim()
    if (!u) return esc(label || '')
    return `<a href="${esc(u)}">${esc(label || u)}</a>`
}

export function buildMarkdown(r) {
    const items = (r.analyses || []).map(a => {
        const fp = a.firstPrinciples || {}
        return [
            `### ${a.name}${typeof a.confidence === 'number' ? ` · confidence ${a.confidence}` : ''}`,
            a.whatItDoes || '',
            a.targetUser ? `**Target user:** ${a.targetUser}` : '',
            `**Core problem:** ${fp.coreProblem || '—'}`,
            `**Why now:** ${fp.whyNow || '—'}`,
            fp.assumptionsChallenged && fp.assumptionsChallenged.length ? `**Assumptions challenged**\n${mdList(fp.assumptionsChallenged)}` : '',
            `**Strengths**\n${mdList(a.strengths)}`,
            `**Weaknesses**\n${mdList(a.weaknesses)}`,
            `**Suggested changes**\n${mdList(a.suggestedChanges)}`,
            `**Pitch**\n\n${a.pitch || '—'}`,
            `**Sources**\n${mdList(a.sources)}`,
        ].filter(Boolean).join('\n\n')
    }).join('\n\n')

    return [
        `# First-Principles Scout — Newly Launched AI Products`,
        `**Window:** ${r.since}  \n**Sources:** ${(r.sources || []).join(', ')}  \n**Products analyzed:** ${(r.analyses || []).length}`,
        `> Research/opinion only. Verify before acting.`,
        r.discoveryNotes && r.discoveryNotes.length ? `## Discovery notes\n${mdList(r.discoveryNotes)}` : '',
        `## Products`,
        items || '_No products found._',
        `---\n_Generated by the first-principles-scout workflow._`,
    ].filter(Boolean).join('\n\n') + '\n'
}

export function buildHtml(r) {
    const cards = (r.analyses || []).map(a => {
        const fp = a.firstPrinciples || {}
        return `
      <article class="card">
        <div class="card-h"><h3>${esc(a.name)}</h3>${typeof a.confidence === 'number' ? `<span class="chip neu">confidence ${esc(a.confidence)}</span>` : ''}</div>
        ${paras(a.whatItDoes)}
        ${a.targetUser ? `<p class="muted">Target: ${esc(a.targetUser)}</p>` : ''}
        <table class="kv">
          <tr><th>Core problem</th><td>${esc(fp.coreProblem || '—')}</td></tr>
          <tr><th>Why now</th><td>${esc(fp.whyNow || '—')}</td></tr>
        </table>
        ${fp.assumptionsChallenged && fp.assumptionsChallenged.length ? `<h4>Assumptions challenged</h4>${htmlList(fp.assumptionsChallenged)}` : ''}
        <div class="two-col">
          <div><h4>Strengths</h4>${htmlList(a.strengths)}</div>
          <div><h4>Weaknesses</h4>${htmlList(a.weaknesses)}</div>
        </div>
        <h4>Suggested changes</h4>${htmlList(a.suggestedChanges)}
        <h4>Pitch</h4>${paras(a.pitch)}
        ${a.sources && a.sources.length ? `<details><summary>Sources (${a.sources.length})</summary>${htmlList(a.sources)}</details>` : ''}
      </article>`
    }).join('')

    const css = `
    *{box-sizing:border-box}
    body{margin:0;background:#0f1115;color:#e8e8ea;font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
    main{max-width:800px;margin:0 auto;padding:64px 24px 96px}
    .masthead{border-bottom:2px solid #3a3f4b;padding-bottom:24px;margin-bottom:8px}
    .eyebrow{letter-spacing:.14em;text-transform:uppercase;font-size:12px;color:#8a90a0;margin:0 0 6px}
    h1{font:800 40px/1.1 "Inter",-apple-system,Helvetica,Arial,sans-serif;margin:0 0 12px}
    h2{font:700 22px/1.3 "Inter",-apple-system,sans-serif;margin:48px 0 12px;padding-bottom:6px;border-bottom:1px solid #2a2e38}
    h3{font-size:17px;margin:0;color:#fff}
    h4{font-size:12px;text-transform:uppercase;letter-spacing:.07em;color:#8a90a0;margin:18px 0 6px}
    p{margin:0 0 14px}.muted{color:#8a90a0}
    a{color:#7aa2ff}
    .disclaimer{color:#8a90a0;font-size:13px;margin:14px 0 0}
    .chip{display:inline-block;padding:3px 12px;border-radius:999px;font-size:13px;font-weight:600;background:#1f2430;color:#aab2c5}
    ul{margin:0 0 14px;padding-left:20px}li{margin:4px 0}
    table.kv{width:100%;border-collapse:collapse;margin:0 0 8px}
    table.kv th{text-align:left;width:130px;color:#8a90a0;font-weight:600;vertical-align:top;padding:6px 12px 6px 0}
    table.kv td{padding:6px 0}
    .cards{display:grid;gap:20px}
    .card{border:1px solid #2a2e38;border-radius:12px;padding:22px;background:#161a22}
    .card-h{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:8px}
    .two-col{display:grid;grid-template-columns:1fr 1fr;gap:24px}@media(max-width:600px){.two-col{grid-template-columns:1fr}}
    details{margin-top:10px}summary{cursor:pointer;color:#8a90a0;font-size:13px}
    footer{margin-top:64px;padding-top:16px;border-top:1px solid #2a2e38;color:#8a90a0;font-size:12px}`

    return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>First-Principles Scout — Newly Launched AI Products</title>
<style>${css}</style>
</head>
<body>
<main>
  <header class="masthead">
    <p class="eyebrow">First-principles scout · ${esc(r.since)}</p>
    <h1>Newly launched AI products</h1>
    <p class="muted">Sources: ${esc((r.sources || []).join(', '))} · ${(r.analyses || []).length} products</p>
  </header>
  <p class="disclaimer">Research/opinion only. Verify before acting.</p>

  <section>
    <h2>Products</h2>
    <div class="cards">${cards || '<p class="muted">No products found.</p>'}
    </div>
  </section>

  <footer>Generated by the first-principles-scout workflow · ${esc(r.since)}</footer>
</main>
</body>
</html>
`
}
